title: I WAS OF THREE MINDS.
permalink: ':title/'

#for local development
#baseurl: ""
#for upload to github
baseurl: "/threeminds" # the subpath of your site, e.g. /blog
url: "https://recfro.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: I WAS OF THREE MINDS # add your name
author-img: figs_threeminds09extended03.jpg # add your photo
about-author: A <a href="https://vimeo.com/566114459">machine learning exhibition</a> by Studio for Narrative Spaces<br>
curated by Zijing Song
studio: RAY LC
social-insta: studiofornarrativespaces # add your handle
social-facebook: rayLCphoto # add your Facebook handle
social-github: recfro # add your Github handle
social-twitter: recfreq # add your Twitter handle
#social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
